steps:

# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# lint
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'lint']
# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
# Deploy
- name: 'gcr.io/intricate-web-420903/firebase'
  args: ['deploy']